# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTIwZTJhNmU5MjBlMzY5Zjg1NGNjMGZhYjJmZjJlMDQ2NjI2YzY3MTgyMmE3ZjFjYjE1YjdiMGQzZTc1NjBkNjExM2IyODg2ZGIwNzFjMWI2ZDFmOWRmMmU1NzEyYzYwNjg5MjEwZGQyOTE5YjIzYTBiNzM1NDFlZjExYWNhOTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
